apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mlflow
  namespace: mlflow
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ad387674789c142cb8fa72d61b47e183-629351163.us-west-2.elb.amazonaws.com`)
      kind: Rule
      services:
        - name: mlflow
          port: 5000