apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mlflow-db-secret
  namespace: mlflow
spec:
  provider: aws
  parameters:
    region: us-west-2
    objects: |
      - objectName: "sandbox-eks/mlflow/db"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: DB_USERNAME
          - path: password
            objectAlias: DB_PASSWORD
          - path: host
            objectAlias: DB_HOST
          - path: port
            objectAlias: DB_PORT
          - path: dbname
            objectAlias: DB_NAME
